spring:
  application:
    name: usuarioservice
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?options=-c%20TimeZone=America/Sao_Paulo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
